"""UI-independent client core: connections, line handling, triggers, commands.

``ClientCore`` owns everything about a session that doesn't depend on how it
is displayed: the open sessions, their connections and logs, line buffering,
gag/highlight/link detection, command history, slash commands and config
reload. Front ends subscribe to it and receive plain event objects; they keep
only per-viewer state (which session is active, scroll position, unread
counts, history navigation).
"""

from __future__ import annotations

import asyncio
import re
from collections import deque
from dataclasses import dataclass, field
from typing import Callable

from rich.text import Text

from .config import Config, Profile, load_config
from .connection import Connection
from .session_log import SessionLog

# How long to wait for more data before flushing a partial line (e.g. a prompt
# with no trailing newline).
PARTIAL_FLUSH_DELAY = 0.08

# Lines of scrollback kept per open session.
SCROLLBACK_LINES = 5000

# Matches http(s) URLs in output. Trailing sentence punctuation is trimmed
# separately so it isn't swept into the link.
_URL_RE = re.compile(r"https?://[^\s\x00-\x1f<>\"'`]+", re.IGNORECASE)
_URL_TRAILING = ".,;:!?)]}>\"'"


# ----- lines and events -------------------------------------------------------


@dataclass
class Line:
    """One line of output, ready for any front end to render.

    ``ansi`` is the text as received (ANSI codes intact, trailing CR removed);
    ``plain`` is its visible text. ``highlights`` and ``links`` are
    ``(start, end, ...)`` ranges into ``plain``. Status lines are lifecycle
    notices generated by the client rather than server output.
    """

    ansi: str
    plain: str
    highlights: list[tuple[int, int, str]] = field(default_factory=list)
    links: list[tuple[int, int, str]] = field(default_factory=list)
    status: bool = False


@dataclass
class SessionOpened:
    conn_id: str


@dataclass
class FocusRequested:
    """The user asked to switch to a session (e.g. ``/connect`` on an open one)."""

    conn_id: str
    origin: object = None


@dataclass
class SessionClosed:
    conn_id: str


@dataclass
class LinesAdded:
    """New lines for a session, delivered together so a front end can decide
    once whether to follow them to the bottom."""

    conn_id: str
    lines: list[Line]


@dataclass
class StateChanged:
    conn_id: str
    state: str


@dataclass
class Cleared:
    conn_id: str


@dataclass
class ConfigReloaded:
    pass


@dataclass
class Notice:
    """A message for the user that isn't part of any session's output."""

    text: str
    severity: str = "information"
    timeout: float | None = None
    origin: object = None


@dataclass
class HelpRequested:
    origin: object = None


@dataclass
class QuitRequested:
    origin: object = None


Event = (
    SessionOpened
    | FocusRequested
    | SessionClosed
    | LinesAdded
    | StateChanged
    | Cleared
    | ConfigReloaded
    | Notice
    | HelpRequested
    | QuitRequested
)


# ----- core -------------------------------------------------------------------


class ClientCore:
    """Connections and session state shared by every front end."""

    def __init__(self, config: Config) -> None:
        self.config = config
        self._config_path = config.source
        self.profiles = config.profiles
        self._by_id = {p.id: p for p in self.profiles}
        self._listeners: list[Callable[[Event], None]] = []
        self._open: list[str] = []
        self._conns: dict[str, Connection] = {}
        self._tasks: dict[str, asyncio.Task] = {}
        self._logs: dict[str, SessionLog] = {}
        self._linebuf: dict[str, str] = {}
        self._flush_handles: dict[str, asyncio.TimerHandle] = {}
        self._scrollback: dict[str, deque[Line]] = {}
        self._states: dict[str, str] = {p.id: "idle" for p in self.profiles}
        self._history: dict[str, list[str]] = {p.id: [] for p in self.profiles}

    # ----- subscribers -----------------------------------------------------

    def subscribe(self, listener: Callable[[Event], None]) -> Callable[[], None]:
        """Call ``listener`` with every event; returns an unsubscribe function."""
        self._listeners.append(listener)
        return lambda: self._listeners.remove(listener)

    def _emit(self, event: Event) -> None:
        for listener in list(self._listeners):
            listener(event)

    # ----- queries ---------------------------------------------------------

    def profile(self, conn_id: str) -> Profile | None:
        return self._by_id.get(conn_id)

    def open_sessions(self) -> list[str]:
        """Connection ids of open sessions, in the order they were opened."""
        return list(self._open)

    def state(self, conn_id: str) -> str:
        return self._states.get(conn_id, "idle")

    def history(self, conn_id: str) -> list[str]:
        return self._history.setdefault(conn_id, [])

    def scrollback(self, conn_id: str) -> list[Line]:
        return list(self._scrollback.get(conn_id, ()))

    def resolve_profile(self, name: str) -> Profile | None:
        """Find a profile by character name, tab name, or connection id."""
        low = name.lower()
        for p in self.profiles:
            if low in (p.char_name.lower(), p.tab_name.lower()) or name == p.id:
                return p
        return None

    # ----- lifecycle -------------------------------------------------------

    async def start(self) -> None:
        """Connect every profile marked ``autoconnect``."""
        for p in self.profiles:
            if p.autoconnect:
                self.connect(p.id)

    async def shutdown(self) -> None:
        """Stop all connections and close all logs."""
        for conn_id in list(self._conns):
            await self.stop_connection(conn_id)
        for log in self._logs.values():
            log.close()
        self._logs.clear()

    # ----- sessions and connections ------------------------------------------

    def open_session(self, conn_id: str) -> None:
        if conn_id in self._open or conn_id not in self._by_id:
            return
        self._open.append(conn_id)
        self._linebuf[conn_id] = ""
        self._scrollback[conn_id] = deque(maxlen=SCROLLBACK_LINES)
        self._emit(SessionOpened(conn_id))

    def connect(self, conn_id: str) -> None:
        """Open the session for a profile (if needed) and start its connection."""
        self.open_session(conn_id)
        self.start_connection(conn_id)

    def start_connection(self, conn_id: str) -> None:
        # A connection that is still running (connected, connecting, or
        # waiting to reconnect) is left alone.
        task = self._tasks.get(conn_id)
        if task is not None and not task.done():
            return
        profile = self._by_id.get(conn_id)
        if profile is None:
            return

        old_log = self._logs.pop(conn_id, None)
        if old_log is not None:
            old_log.close()
        self._logs[conn_id] = SessionLog(self.config.log_dir, profile.char_name)
        self.status(conn_id, f"--- session log: {self._logs[conn_id].path} ---")

        conn = Connection(
            profile,
            on_text=lambda t, cid=conn_id: self._append_text(cid, t),
            on_status=lambda t, cid=conn_id: self.status(cid, t),
            on_state=lambda s, cid=conn_id: self._set_state(cid, s),
        )
        self._conns[conn_id] = conn
        self._tasks[conn_id] = asyncio.create_task(conn.run())

    async def stop_connection(self, conn_id: str) -> None:
        conn = self._conns.get(conn_id)
        if conn is not None:
            await conn.close()
        task = self._tasks.pop(conn_id, None)
        if task is not None:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass

    async def close_session(self, conn_id: str) -> None:
        """Stop a session's connection and forget its output."""
        await self.stop_connection(conn_id)
        if conn_id not in self._open:
            return
        handle = self._flush_handles.pop(conn_id, None)
        if handle is not None:
            handle.cancel()
        self._open.remove(conn_id)
        self._linebuf[conn_id] = ""
        self._scrollback.pop(conn_id, None)
        self._states[conn_id] = "idle"
        log = self._logs.pop(conn_id, None)
        if log is not None:
            log.close()
        self._emit(SessionClosed(conn_id))

    def clear(self, conn_id: str) -> None:
        if conn_id in self._scrollback:
            self._scrollback[conn_id].clear()
        self._emit(Cleared(conn_id))

    def _set_state(self, conn_id: str, state: str) -> None:
        self._states[conn_id] = state
        self._emit(StateChanged(conn_id, state))

    # ----- output ----------------------------------------------------------

    def _add_lines(self, conn_id: str, lines: list[Line]) -> None:
        if not lines:
            return
        self._scrollback[conn_id].extend(lines)
        self._emit(LinesAdded(conn_id, lines))

    def render_line(self, conn_id: str, raw: str) -> Line | None:
        """Build a line, or ``None`` if a gag drops it.

        Gag matching runs against the visible (ANSI-stripped) text.
        """
        ansi = raw.rstrip("\r")
        plain = Text.from_ansi(ansi).plain
        profile = self._by_id[conn_id]
        if any(rx.search(plain) for rx in profile.gags):
            return None
        highlights = [
            (m.start(), m.end(), hl.style)
            for hl in profile.highlights
            for m in hl.pattern.finditer(plain)
            if m.start() != m.end()
        ]
        return Line(ansi, plain, highlights, find_links(plain))

    def _emit_lines(self, conn_id: str, raw_lines: list[str]) -> None:
        """Render, record, and log output lines (dropping gagged ones)."""
        lines = []
        for raw in raw_lines:
            line = self.render_line(conn_id, raw)
            if line is None:
                continue
            lines.append(line)
            log = self._logs.get(conn_id)
            if log is not None:
                log.write(line.plain + "\n")
        self._add_lines(conn_id, lines)

    def _append_text(self, conn_id: str, text: str) -> None:
        """Buffer incoming text and emit complete lines."""
        if conn_id not in self._open:
            return
        buffer = self._linebuf.get(conn_id, "") + text
        *lines, remainder = buffer.split("\n")
        self._emit_lines(conn_id, lines)
        self._linebuf[conn_id] = remainder
        self._schedule_partial_flush(conn_id)

    def _schedule_partial_flush(self, conn_id: str) -> None:
        handle = self._flush_handles.get(conn_id)
        if handle is not None:
            handle.cancel()
        self._flush_handles[conn_id] = asyncio.get_running_loop().call_later(
            PARTIAL_FLUSH_DELAY, self._flush_partial, conn_id
        )

    def _flush_partial(self, conn_id: str) -> None:
        remainder = self._linebuf.get(conn_id, "")
        if remainder:
            self._linebuf[conn_id] = ""
            if conn_id in self._open:
                self._emit_lines(conn_id, [remainder])

    def status(self, conn_id: str, text: str) -> None:
        """Add a status notice to a session's output (not logged)."""
        # Flush any pending partial line so status notices stay in order.
        self._flush_partial(conn_id)
        if conn_id not in self._open:
            return
        self._add_lines(conn_id, [Line(text, text, status=True)])

    # ----- input -----------------------------------------------------------

    async def submit(
        self, conn_id: str | None, command: str, origin: object = None
    ) -> None:
        """Handle a line typed by the user while ``conn_id`` is active.

        ``origin`` identifies the front end that sent it. Replies meant only
        for that user (notices, help, focus and quit requests) carry it, so a
        front end serving several viewers can route them.
        """
        if command.startswith("/"):
            await self._handle_slash(conn_id, command, origin)
            return
        if conn_id is None:
            return
        self._record_history(conn_id, command)
        conn = self._conns.get(conn_id)
        if conn is not None:
            await conn.send(command)
        else:
            self.status(conn_id, "Not connected. Press F5 or use /connect.")

    def _record_history(self, conn_id: str, command: str) -> None:
        history = self.history(conn_id)
        if command.strip() and (not history or history[-1] != command):
            history.append(command)

    async def _handle_slash(
        self, conn_id: str | None, command: str, origin: object = None
    ) -> None:
        parts = command[1:].split()
        name = parts[0].lower() if parts else ""
        arg = " ".join(parts[1:]) if len(parts) > 1 else None
        if name in ("connect", "c"):
            self._cmd_connect(conn_id, arg, origin)
        elif name in ("disconnect", "dc"):
            if conn_id is None:
                self._emit(Notice("No active connection to disconnect.", origin=origin))
                return
            await self.close_session(conn_id)
        elif name in ("reconnect", "rc"):
            if conn_id is None:
                self._emit(Notice("No active connection to reconnect.", origin=origin))
                return
            await self.stop_connection(conn_id)
            self.start_connection(conn_id)
        elif name == "clear":
            if conn_id is not None:
                self.clear(conn_id)
        elif name == "reload":
            self.reload(origin)
        elif name in ("quit", "q", "exit"):
            self._emit(QuitRequested(origin))
        elif name == "help":
            self._emit(HelpRequested(origin))
        else:
            self._emit(Notice(f"Unknown command: /{name} (try /help)", origin=origin))

    def _cmd_connect(
        self, conn_id: str | None, arg: str | None, origin: object = None
    ) -> None:
        if arg is None:
            if conn_id is not None:
                self.start_connection(conn_id)
            else:
                names = ", ".join(p.char_name for p in self.profiles)
                self._emit(Notice(
                    f"Usage: /connect <character>. Available: {names}", origin=origin
                ))
            return
        profile = self.resolve_profile(arg)
        if profile is None:
            self._emit(Notice(f"Unknown character: {arg}", origin=origin))
            return
        self.connect(profile.id)
        self._emit(FocusRequested(profile.id, origin))

    def reload(self, origin: object = None) -> None:
        """Re-read the config file and apply it without restarting.

        New characters become available immediately; trigger (gag/highlight)
        and tab-name changes apply to open sessions at once. Connection
        settings (host/port/tls/...) take effect on the next (re)connect. Open
        sessions whose character was removed from the config keep working with
        their old profile until closed.
        """
        if not self._config_path:
            self._emit(Notice("No config file to reload.", "warning", origin=origin))
            return
        try:
            config = load_config(self._config_path)
        except (FileNotFoundError, ValueError) as exc:
            self._emit(Notice(f"Reload failed: {exc}", "error", 10, origin))
            return

        self.config = config
        self.profiles = config.profiles
        new_by_id = {p.id: p for p in config.profiles}
        # Preserve profiles for open sessions that vanished, so rendering and
        # labels keep working until those sessions are closed.
        for cid in self._open:
            if cid not in new_by_id and cid in self._by_id:
                new_by_id[cid] = self._by_id[cid]
        self._by_id = new_by_id

        for p in config.profiles:
            self._states.setdefault(p.id, "idle")
            self._history.setdefault(p.id, [])
            self._linebuf.setdefault(p.id, "")

        self._emit(ConfigReloaded())
        self._emit(
            Notice(
                f"Reloaded {self._config_path} — {len(config.profiles)} character(s).",
                timeout=6,
                origin=origin,
            )
        )


def find_links(plain: str) -> list[tuple[int, int, str]]:
    """``(start, end, url)`` for each http(s) URL in ``plain``."""
    links = []
    for match in _URL_RE.finditer(plain):
        start, end = match.start(), match.end()
        url = match.group()
        while url and url[-1] in _URL_TRAILING:
            ch = url[-1]
            # Keep a closing bracket that pairs with one inside the URL
            # (e.g. Wikipedia links), strip it only when unbalanced.
            pair = {")": "(", "]": "[", "}": "{"}.get(ch)
            if pair and url.count(pair) >= url.count(ch):
                break
            url = url[:-1]
            end -= 1
        if url:
            links.append((start, end, url))
    return links
